# Various app settings can be defined in the viktor.config.toml file.
# For more information, see: https://docs.viktor.ai/docs/create-apps/fundamentals/#viktorconfigtoml
app_type = 'simple'  # 'simple' | 'tree'
python_version = '3.10'  # '3.7' | '3.8' | '3.9' | '3.10'
